
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weddinverse-api-dev
  labels:
    app: weddinverse-api-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: weddinverse-api-dev
  template:
    metadata:
      labels:
        app: weddinverse-api-dev
    spec:
      containers:
      - name: weddinverse-api-dev
        image: asia-south1-docker.pkg.dev/ken-cloud-436408/weddinverse-api/dev:latest
        ports:
        - containerPort: 4000
        envFrom:
          - secretRef:
              name: weddinverse-api-dev
---
apiVersion: v1
kind: Service
metadata:
  name: weddinverse-api-dev
  labels:
    app: weddinverse-api-dev
spec:
  ports:
    - name: api
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: weddinverse-api-dev
  type: LoadBalancer
